# Base image
FROM openjdk:17-jdk-slim as build-stage

# Set the working directory in the container
WORKDIR /app

# Copy the Gradle project files
COPY . /app

RUN sed -i 's/\r$//' gradlew && chmod +x gradlew

# Copy the source code

# Build the application
RUN bash ./gradlew build -x test

# Base image
FROM openjdk:17-jdk-slim as production-stage

# Set the working directory in the container
WORKDIR /app

# Copy the jar file
COPY --from=build-stage /app/build/libs/weather-0.0.1-SNAPSHOT.jar /app

# Expose the port
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "/app/weather-0.0.1-SNAPSHOT.jar"]


